title: Syamantak Payra # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Researcher. Maker. Inventor.
  <br>
  <br>
  Passionate about developing technologies with human impact.
  <br>
  <br>
  MIT Class of 2022
  <br>
  <small>
      Electrical Engineering and Computer Science
  </small>
  <br>
  <small>
      Public Policy Minor. Entrepreneurship Minor.
  </small>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/syamantak-payra/">View my LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-104667365-1 # your Google Analytics tracking ID here
markdown: CommonMarkGhPages
